name: Build Orchestrator

on:
  push:
    branches: [main]
    paths:
      - "src/orchestrator/**"
      - ".github/workflows/build-orchestrator.yml"
  pull_request:
    paths:
      - "src/orchestrator/**"
      - ".github/workflows/build-orchestrator.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
          check-latest: true
          cache: true

      - name: Go version
        run: go version

      - name: Download modules
        working-directory: src/orchestrator
        run: go mod download

      - name: Build orchestrator
        working-directory: src/orchestrator/cmd
        run: go build -v -o ../builds/cube-orchestrator_ci main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cube-orchestrator_ci-linux-amd64
          path: src/orchestrator/builds/cube-orchestrator_ci
