name: Docs Quality

on:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs-quality.yml"
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "README.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            README.md
            docs/**/*.md

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links with Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config lychee.toml
            README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
